project:
  type: book

book:
  title: "Angewandte Baumbiologie"
  author: "Steffen Rust"
  date: last-modified
  date-format: D. MMMM YYYY
  chapters:
    - index.qmd
    - intro.qmd
    - WHH.qmd
    - Stress.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
lang: de

format:
  html:
    theme: cosmo



