project:
  type: book

book:
  title: "Angewandte Baumbiologie"
  author: "Steffen Rust"
  date: last-modified
  date-format: D. MMMM YYYY
  chapters:
    - index.qmd
    - intro.qmd
    - 2015_OS_Baumstamm.qmd
    - WHH.qmd
    - Stress.qmd
    - Vitalitaet.qmd
    - references.qmd

bibliography: ["d:/users/Steffen/Documents/Literatur/BiBTeX/Alles.bib", "d:/users/Steffen/Documents/Literatur/BiBTeX/Zotero.bib"]
lang: de

format:
  html:
    theme: cosmo
  pdf:
    papersize: a4
    keep-tex: true



