# Wurzel

## Aufgaben

Baumwurzeln haben eine ganze Reihe von Funktionen, z. B.:
- Verankerung des Baumes im Boden
- Aufnahme von Wasser und Nährstoffen
- Speicherung von Nährstoffen
- Umverteilung von Wasser
- Austausch von Nährstoffen und Wasser mit Pilzen, Bakterien und anderen Bäumen

## Form des Wurzelsystems

Zwar wird oft von verschiedenen Wurzelsystemtypen gesprochen, z. B. Pfahlwurzel, Herzwurzel, Flachwurzel, aber in der Realität sind diese, insbesondere im städtischen Umfeld, selten ausgeprägt. Das Wurzelwachstum ist in erster Linie opportunistisch, d. h. die Wurzeln wachsen dort, wo sie die besten Bedingungen vorfinden.

Die Form des Wurzelsystems wird durch eine Reihe von Faktoren beeinflusst, z. B.:
- Bodenschichtung
- Bodenfeuchteverteilung
- Bodenverdichtung
- Bodenversiegelung

Die Wurzeln eines Baumes sind in der Regel so groß wie die Krone. Sie können sich aber auch über eine Fläche ausbreiten, die 2-3 mal so groß ist wie die Krone. Die Wurzeln eines Baumes sind in der Regel nicht tiefer als 1,5 m. Die Wurzeln eines Baumes können bis zu 100 m lang sein.